name: turboget
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  connectivity_plus: ^6.0.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0
  http: ^1.2.0
  system_alert_window: ^2.0.7
  video_player: ^2.8.0
  chewie: ^1.8.0
  mime: ^1.0.4
  youtube_explode_dart: ^2.0.2
  html: ^0.15.4
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
